import type { ActionKey } from "../types";

export const ACTIONS_LIST: ActionKey[] = [
  "PROCEED_MAPPING",
  "NEED_HOTEL_REVIEW",
  "NEED_ROOM_REVIEW",
  "NEED_STAKEHOLDER_CONFIRMATION",
  "REQUEST_AGENT_AMENDMENT",
  "REQUEST_NEW_HOTEL_CREATION",
  "REQUEST_NEW_ROOM_CREATION",
  "NO_ACTION_NEEDED",
];
