import type { ParsedFile } from "../types";

// Sample API report — headers intentionally match the canonical names so
// auto-mapping resolves cleanly. Used by the "Load sample data" button.
export const SAMPLE_FILE: ParsedFile = {
  fileName: "sample_api_report.csv",
  headers: [
    "Supplier",
    "Hotel ID",
    "Hotel Name",
    "Country",
    "City",
    "Address",
    "Active Status",
    "Mapping Status",
    "Hotel Creation Type",
    "Room Name",
    "Bed Type",
    "Extra Bed Type",
    "Internal Hotel Name",
    "Internal Address",
    "Internal Room Name",
    "Internal Bed Type",
    "Internal Extra Bed Type",
  ],
  rows: [
    {
      Supplier: "Agent A",
      "Hotel ID": "KR001",
      "Hotel Name": "Lotte Hotel Seoul",
      Country: "Korea",
      City: "Seoul",
      Address: "30 Eulji-ro, Jung-gu, Seoul",
      "Active Status": "Active",
      "Mapping Status": "Unmapped",
      "Hotel Creation Type": "Old Hotel",
      "Room Name": "Deluxe Double Room",
      "Bed Type": "Double",
      "Extra Bed Type": "Single Bed",
      "Internal Hotel Name": "LOTTE HOTEL SEOUL",
      "Internal Address": "30 Eulji-ro, Jung-gu, Seoul",
      "Internal Room Name": "Deluxe Double",
      "Internal Bed Type": "Double",
      "Internal Extra Bed Type": "Single Bed",
    },
    {
      Supplier: "Agent B",
      "Hotel ID": "JP002",
      "Hotel Name": "Kyoto Ryokan Sakura",
      Country: "Japan",
      City: "Kyoto",
      Address: "1-2-3 Gion, Kyoto",
      "Active Status": "Active",
      "Mapping Status": "Partial Mapped",
      "Hotel Creation Type": "Old Hotel",
      "Room Name": "Japanese Style Room",
      "Bed Type": "Futon",
      "Extra Bed Type": "Tatami",
      "Internal Hotel Name": "Kyoto Sakura Ryokan",
      "Internal Address": "1-2-4 Gion, Kyoto",
      "Internal Room Name": "Japanese Room",
      "Internal Bed Type": "Futon",
      "Internal Extra Bed Type": "Single Bed",
    },
    {
      Supplier: "Agent C",
      "Hotel ID": "VN003",
      "Hotel Name": "Ocean Bay Resort Phu Quoc",
      Country: "Vietnam",
      City: "Phu Quoc",
      Address: "Ong Lang Beach, Phu Quoc",
      "Active Status": "Active",
      "Mapping Status": "Unmapped",
      "Hotel Creation Type": "Newly Created Hotel",
      "Room Name": "Ocean View Villa",
      "Bed Type": "King",
      "Extra Bed Type": "",
      "Internal Hotel Name": "",
      "Internal Address": "",
      "Internal Room Name": "",
      "Internal Bed Type": "",
      "Internal Extra Bed Type": "",
    },
    {
      Supplier: "Agent A",
      "Hotel ID": "TH004",
      "Hotel Name": "Bangkok Riverside Hotel",
      Country: "Thailand",
      City: "Bangkok",
      Address: "12 Charoen Krung Rd, Bangkok",
      "Active Status": "Active",
      "Mapping Status": "Mapped",
      "Hotel Creation Type": "Old Hotel",
      "Room Name": "Superior King",
      "Bed Type": "King",
      "Extra Bed Type": "Sofa Bed",
      "Internal Hotel Name": "Bangkok Riverside Hotel",
      "Internal Address": "12 Charoen Krung Rd, Bangkok",
      "Internal Room Name": "Superior King",
      "Internal Bed Type": "Queen",
      "Internal Extra Bed Type": "Sofa Bed",
    },
    {
      Supplier: "Agent D",
      "Hotel ID": "ID005",
      "Hotel Name": "Bali Sunset Villas",
      Country: "Indonesia",
      City: "Bali",
      Address: "Jl. Pantai Berawa, Canggu, Bali",
      "Active Status": "Inactive",
      "Mapping Status": "Mapped",
      "Hotel Creation Type": "Old Hotel",
      "Room Name": "One Bedroom Pool Villa",
      "Bed Type": "King",
      "Extra Bed Type": "Rollaway",
      "Internal Hotel Name": "Bali Sunset Villa",
      "Internal Address": "Jl. Pantai Berawa, Canggu, Bali",
      "Internal Room Name": "1BR Pool Villa",
      "Internal Bed Type": "King",
      "Internal Extra Bed Type": "Rollaway",
    },
  ],
};
